 SELECT EF_NOTAS.EMPRESAID,
           EF_NOTAS.NOTAID,
           EF_NOTAS.DATAEMISSAOID,
           EF_NOTAS.PEDIDOID,
           EF_NOTAS.DATAPEDIDOID,
           EF_NOTAS.TIPOMOVIMENTO,
           EF_PRODUTO.GRUPOID,
           EF_PRODUTO.SUBGRUPOID,
           EF_NOTAS.QUANTIDADE,
           EF_NOTAS.VLRLIQUIDO,
           EF_NFS.VLRTOTALNOTA,
           (CASE
             WHEN EF_NOTAS.TIPOMOVIMENTO = 'S' THEN
              QUANTIDADE
             WHEN EF_NOTAS.TIPOMOVIMENTO = 'E' THEN
              QUANTIDADE * -1
           END) QTD
      FROM EF_NOTAS, EF_PRODUTO, EF_NFS
     WHERE EF_NOTAS.EMPRESAID = EF_PRODUTO.EMPRESAID(+)
       AND EF_NOTAS.PRODUTOID = EF_PRODUTO.PRODUTOID(+)
       AND EF_NOTAS.EMPRESAID = EF_NFS.EMPRESAID
       AND EF_NOTAS.NOTAID = EF_NFS.NFSID
       AND EF_NOTAS.DATAEMISSAOID = EF_NOTAS.DATAEMISSAOID
       AND SIGLA_DEPTO = 'COM'
       AND EF_NOTAS.DATAEMISSAOID >= '01/04/2006'
       AND EF_NOTAS.PRODUTOID IS NOT NULL
       AND EF_PRODUTO.SUBGRUPOID = 8
     ORDER BY EF_NOTAS.EMPRESAID,
              EF_NOTAS.NOTAID,
              EF_NOTAS.DATAEMISSAOID
