CREATE OR REPLACE PROCEDURE LOGINGSI( P_USUARIO IN VARCHAR2,
                                      P_SENHA IN VARCHAR2,
                                      P_IP IN VARCHAR2,
                                      P_NOMEMAQUINA IN VARCHAR2,
                                      P_RESULT OUT NUMBER )
IS
  TESTE GSI.AS_USERATIVO.USUARIOID%TYPE;
  ID GSI.AS_USERATIVO.USERATIVOSID%TYPE;
BEGIN
  IF P_SENHA IS NULL THEN
     SELECT USUARIOID INTO TESTE
       FROM GSI.AS_USUARIO
      WHERE USUARIOID = P_USUARIO;
  ELSE
     SELECT USUARIOID INTO TESTE
       FROM GSI.AS_USUARIO
      WHERE USUARIOID = P_USUARIO
        AND SENHA = P_SENHA;
  END IF;

  IF TESTE IS NOT NULL THEN
     SELECT ( NVL( MAX( USERATIVOSID ), 0 ) + 1 ) INTO ID FROM GSI.AS_USERATIVO;
     INSERT INTO GSI.AS_USERATIVO VALUES( ID, '', P_USUARIO, SYSDATE, P_IP, P_NOMEMAQUINA );
     P_RESULT := ID;
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    P_RESULT := 0;
END;
/
