CREATE OR REPLACE PROCEDURE LOGOUTGSI( P_USUARIOID IN NUMBER )
IS
  TESTA GSI.AS_USERATIVO.USERATIVOSID%TYPE;
BEGIN
  SELECT USERATIVOSID INTO TESTA
    FROM GSI.AS_USERATIVO
   WHERE USERATIVOSID = P_USUARIOID;

  IF TESTA IS NOT NULL THEN
     DELETE FROM GSI.AS_USERATIVO WHERE USERATIVOSID = P_USUARIOID;
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    TESTA := 0;
END;
/
